language: cpp
dist: trusty

branches:
  only:
  - master
  - testing

script:
- mkdir -p build
- cd build
- cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..
- make
- ./moirai_test
- ./moirai_test_api
