version: 1.0.{build}

image: Visual Studio 2019

platform: x64

environment:
  PLATFORM: x64

configuration: Release

branches:
  only:
  - main
  - testing

build_script:
- cmd: >-
    msbuild tests\moirai_test.sln /p:Platform="x64" /p:Configuration=Debug /consoleloggerparameters:ErrorsOnly

test_script:
- cmd: >-
    tests\x64\Debug\moirai_test.exe
    
    tests\x64\Debug\moirai_test_api.exe
