version: 1.0.{build}

image:
- Visual Studio 2017
# - Visual Studio 2015

platform: x64

environment:
  matrix:
  - PLATFORM: x64
  # - PLATFORM: x86

branches:
  only:
  - master, devel

build_script:
- cmd: >-
    msbuild tests\moirai_test.sln /p:Platform="x64" /p:Configuration=Debug /consoleloggerparameters:ErrorsOnly

test_script:
- cmd: >-
    tests\x64\Debug\moirai_test.exe
    
    tests\x64\Debug\moirai_test_api.exe
